server:
  port: 8083

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:mysql://${DB_HOST:investment-tracker-db.cr0cww8oy52m.ap-south-1.rds.amazonaws.com}:3306/${DB_NAME:investment_tracker_db}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:Mumbai#$11}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: 5672
    username: guest
    password: guest

app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-super-secure-secret-key-change-in-production}
    access-token-expiry-ms: 3600000        # 1 hour
    refresh-token-expiry-ms: 604800000     # 7 days
  
  tenant-service:
    url: ${TENANT_SERVICE_URL:http://tenant-service:8082}

logging:
  level:
    com.investtracker.auth: DEBUG
    org.springframework.security: INFO
